<#
Reads version.json and propagates engine semver to build artifacts.

Usage:
  powershell -File scripts/sync-version.ps1
  . ./scripts/sync-version.ps1; $env:CTRACK_ENGINE_VERSION
#>

param(
  [string]$VersionFile = (Join-Path $PSScriptRoot "..\version.json"),
  [string]$RepoRoot = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

function Write-Utf8NoBomFile {
  param(
    [Parameter(Mandatory = $true)][string]$Path,
    [Parameter(Mandatory = $true)][string]$Content
  )
  $utf8NoBom = New-Object System.Text.UTF8Encoding($false)
  [System.IO.File]::WriteAllText($Path, $Content, $utf8NoBom)
}

if (-not (Test-Path -LiteralPath $VersionFile)) {
  throw "Version file not found: $VersionFile"
}

$versionData = Get-Content -LiteralPath $VersionFile -Raw | ConvertFrom-Json
$engineVersion = [string]$versionData.engine
$webVersion = [string]$versionData.web
$nukeVersion = [string]$versionData.nukePlugin

if ($engineVersion -notmatch "^\d+\.\d+\.\d+$") {
  throw "version.json engine must be semver X.Y.Z. Got: '$engineVersion'"
}

$generatedDir = Join-Path $RepoRoot "engine\src\generated"
if (-not (Test-Path -LiteralPath $generatedDir)) {
  New-Item -ItemType Directory -Path $generatedDir -Force | Out-Null
}

$versionTsPath = Join-Path $generatedDir "engine-version.ts"
$versionTs = @"
/** Generated by scripts/sync-version.ps1 — do not edit manually. */
export const ENGINE_VERSION = "$engineVersion"
"@
Write-Utf8NoBomFile -Path $versionTsPath -Content ($versionTs + [Environment]::NewLine)

$enginePackagePath = Join-Path $RepoRoot "engine\package.json"
$enginePackage = Get-Content -LiteralPath $enginePackagePath -Raw | ConvertFrom-Json
$enginePackage.version = $engineVersion
Write-Utf8NoBomFile -Path $enginePackagePath -Content (($enginePackage | ConvertTo-Json -Depth 20) + [Environment]::NewLine)

$webPackagePath = Join-Path $RepoRoot "web\package.json"
if (Test-Path -LiteralPath $webPackagePath) {
  $webPackage = Get-Content -LiteralPath $webPackagePath -Raw | ConvertFrom-Json
  $webPackage.version = $webVersion
  Write-Utf8NoBomFile -Path $webPackagePath -Content (($webPackage | ConvertTo-Json -Depth 20) + [Environment]::NewLine)
}

$versionStampPath = Join-Path $RepoRoot "scripts\.engine-version"
Set-Content -LiteralPath $versionStampPath -Value ($engineVersion + [Environment]::NewLine) -Encoding ASCII -NoNewline
Add-Content -LiteralPath $versionStampPath -Value "" -Encoding ASCII

[Environment]::SetEnvironmentVariable("CTRACK_ENGINE_VERSION", $engineVersion, "Process")
[Environment]::SetEnvironmentVariable("CTRACK_NUKE_VERSION", $nukeVersion, "Process")

Write-Host "[sync-version] engine=$engineVersion nuke=$nukeVersion web=$webVersion"
