<#
.SYNOPSIS
  Write a facility engine .env for installer bundling (from env vars / GitHub Actions secrets).

.DESCRIPTION
  Never commit the output file. CI writes this into the release payload via CTRACK_BUNDLE_ENV=1
  so installed engines have Supabase auth (and optional storage) without manual .env copy.

.EXAMPLE
  powershell -File scripts/write-engine-bundle-env.ps1 -OutputPath .release/engine-bundle.env
#>

param(
  [Parameter(Mandatory = $true)]
  [string]$OutputPath,
  [switch]$IncludeStorage
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

. (Join-Path $PSScriptRoot "load-deploy-env.ps1")
Import-CtrackDeployEnv | Out-Null

function Get-EnvTrim([string]$Name) {
  $v = [Environment]::GetEnvironmentVariable($Name)
  if ($null -eq $v) { return "" }
  return $v.Trim().Trim('"').Trim("'")
}

$supabaseUrl = Get-EnvTrim "VITE_SUPABASE_URL"
if (-not $supabaseUrl) { $supabaseUrl = Get-EnvTrim "SUPABASE_URL" }
$anonKey = Get-EnvTrim "VITE_SUPABASE_ANON_KEY"
if (-not $anonKey) { $anonKey = Get-EnvTrim "SUPABASE_ANON_KEY" }

if (-not $supabaseUrl -or -not $anonKey) {
  throw "Missing VITE_SUPABASE_URL (or SUPABASE_URL) and VITE_SUPABASE_ANON_KEY. Set GitHub Actions secrets before release."
}

$webUrl = Get-EnvTrim "CTRACK_WEB_URL"
if (-not $webUrl) { $webUrl = "https://ctrackpublishweb.vercel.app" }

$origins = Get-EnvTrim "CTRACK_WEB_ORIGINS"
if (-not $origins) {
  $origins = "https://ctrackpublishweb.vercel.app,http://localhost:5173,http://127.0.0.1:5173"
}

$authCallback = Get-EnvTrim "CTRACK_AUTH_CALLBACK_URL"
if (-not $authCallback) { $authCallback = "http://127.0.0.1:7777/auth/link" }

$lines = [System.Collections.Generic.List[string]]::new()
[void]$lines.Add("# Generated by scripts/write-engine-bundle-env.ps1 - do not commit")
[void]$lines.Add("# $(Get-Date -Format o)")
[void]$lines.Add("VITE_SUPABASE_URL=$supabaseUrl")
[void]$lines.Add("VITE_SUPABASE_ANON_KEY=$anonKey")
[void]$lines.Add("SUPABASE_URL=$supabaseUrl")
[void]$lines.Add("CTRACK_WEB_URL=$webUrl")
[void]$lines.Add("CTRACK_WEB_ORIGINS=$origins")
[void]$lines.Add("CTRACK_AUTH_CALLBACK_URL=$authCallback")

$wantStorage = $IncludeStorage -or ((Get-EnvTrim "CTRACK_BUNDLE_STORAGE") -match '^(1|true|yes)$')
if ($wantStorage) {
  $storageKeys = @(
    "STORAGE_PROVIDER",
    "AWS_ACCESS_KEY_ID",
    "AWS_SECRET_ACCESS_KEY",
    "AWS_REGION",
    "AWS_S3_BUCKET_NAME",
    "HYBRID_STORAGE_PRIMARY_ENDPOINT",
    "HYBRID_STORAGE_PRIMARY_ACCESS_KEY",
    "HYBRID_STORAGE_PRIMARY_SECRET_KEY",
    "HYBRID_STORAGE_PRIMARY_BUCKET",
    "HYBRID_STORAGE_PRIMARY_REGION"
  )
  $anyStorage = $false
  foreach ($k in $storageKeys) {
    $v = Get-EnvTrim $k
    if ($v) {
      [void]$lines.Add("$k=$v")
      $anyStorage = $true
    }
  }
  if ($anyStorage -and -not (Get-EnvTrim "STORAGE_PROVIDER")) {
    [void]$lines.Add("STORAGE_PROVIDER=hybrid")
  }
}

$outDir = Split-Path -Parent $OutputPath
if ($outDir -and -not (Test-Path -LiteralPath $outDir)) {
  New-Item -ItemType Directory -Path $outDir -Force | Out-Null
}

$utf8 = New-Object System.Text.UTF8Encoding $false
[System.IO.File]::WriteAllLines($OutputPath, $lines.ToArray(), $utf8)

$count = $lines.Count
$keyLen = $anonKey.Length
Write-Host "[bundle-env] Wrote $OutputPath ($count lines; anon key length=$keyLen)"
